#!/usr/bin/env python3
"""Compute metric-matched fallback @font-face rules for app/fonts.css.

The webfonts load with `font-display: swap`, so text paints in a fallback face
first and is replaced when the real bytes land. Left alone that reflows the
page — badly, at a 127px Anton headline. Overriding the fallback's metrics so
its line box and average advance match the webfont makes the swap near-invisible.

    sizeAdjust    = avgAdvance(web) / avgAdvance(fallback)
    ascentOverride  = ascent(web)  / sizeAdjust
    descentOverride = descent(web) / sizeAdjust
    lineGapOverride = lineGap(web) / sizeAdjust

Re-run whenever a webfont is swapped or resubsetted, and paste the output into
app/fonts.css:

    python3 scripts/build-font-fallbacks.py

Requires: fonttools, brotli (for the woff2 subsets).
"""

import pathlib
import string

from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEBFONTS = ROOT / "public" / "fonts"
SYSTEM = pathlib.Path("/System/Library/Fonts/Supplemental")

# Sampled over the Latin letters the subsets actually carry; the display face is
# uppercase-only in use, but averaging both cases keeps the body face honest.
SAMPLE = string.ascii_letters + " "

PAIRS = [
    {
        "name": "Anton Fallback",
        "web": WEBFONTS / "anton-400.woff2",
        "local": SYSTEM / "Arial Narrow.ttf",
        # Ordered by how close each is to Anton's condensed proportions.
        "locals": ["Arial Narrow", "Liberation Sans Narrow", "DejaVu Sans Condensed"],
    },
    {
        "name": "Barlow Fallback",
        "web": WEBFONTS / "barlow-400.woff2",
        "local": SYSTEM / "Arial.ttf",
        "locals": ["Arial", "Helvetica", "Liberation Sans"],
    },
]


def measure(path: pathlib.Path) -> dict:
    font = TTFont(str(path), fontNumber=0)
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    os2, hhea = font["OS/2"], font["hhea"]

    widths = [hmtx[cmap[ord(c)]][0] for c in SAMPLE if ord(c) in cmap]
    use_typo = bool(os2.fsSelection & (1 << 7))
    return {
        "avg": sum(widths) / len(widths) / upm,
        "asc": (os2.sTypoAscender if use_typo else hhea.ascent) / upm,
        "desc": abs(os2.sTypoDescender if use_typo else hhea.descent) / upm,
        "gap": (os2.sTypoLineGap if use_typo else hhea.lineGap) / upm,
    }


def main() -> None:
    print("/* Generated by scripts/build-font-fallbacks.py — do not hand-edit. */")
    for pair in PAIRS:
        if not pair["local"].exists():
            print(f"/* skipped {pair['name']}: {pair['local']} not found */")
            continue

        web, fallback = measure(pair["web"]), measure(pair["local"])
        adjust = web["avg"] / fallback["avg"]
        src = ", ".join(f'local("{n}")' for n in pair["locals"])

        print(f"""
@font-face {{
  font-family: "{pair['name']}";
  src: {src};
  size-adjust: {adjust * 100:.2f}%;
  ascent-override: {web['asc'] / adjust * 100:.2f}%;
  descent-override: {web['desc'] / adjust * 100:.2f}%;
  line-gap-override: {web['gap'] / adjust * 100:.2f}%;
}}""")


if __name__ == "__main__":
    main()
